;; NOTE: If you change behavior here, update docs/editor.md :)
;; Editor glue: main update loop, drawing/overlay functions
(in-package #:mmorpg)

(defun update-editor (editor game dt)
  ;; Update editor input, camera, and painting when active.
  (let* ((world (game-world game))
         (camera (game-camera game))
         (ui (game-ui game))
         (assets (game-assets game)))
    (when (editor-active editor)
      (update-editor-status editor dt)
      (unless (ui-menu-open ui)
        (editor-update-mode editor)
        (editor-handle-zone-actions editor game)
        (when (raylib:is-key-pressed +key-q+)
          (cond
            ((eq (editor-mode editor) :spawn)
             (editor-adjust-spawn editor -1))
            ((eq (editor-mode editor) :object)
             (editor-adjust-object editor -1))
            ((member (editor-mode editor) '(:tile :collision))
             (editor-adjust-tileset editor game assets -1))))
        (when (raylib:is-key-pressed +key-e+)
          (cond
            ((eq (editor-mode editor) :spawn)
             (editor-adjust-spawn editor 1))
            ((eq (editor-mode editor) :object)
             (editor-adjust-object editor 1))
            ((member (editor-mode editor) '(:tile :collision))
             (editor-adjust-tileset editor game assets 1))))
        (editor-handle-tileset-picker editor)
        (when (raylib:is-key-pressed +key-f5+)
          (editor-export-zone editor world))
        (editor-update-camera editor world dt)
        (editor-apply-paint editor world camera)))))

(defun draw-editor-spawns (editor world)
  ;; Draw spawn markers in world space while editing.
  (let ((zone (world-zone world)))
    (when zone
      (let* ((tile-size (world-tile-dest-size world))
             (size (round tile-size))
             (dot (max 2 (round (* size 0.2)))))
        (dolist (spawn (zone-spawns zone))
          (let ((tx (getf spawn :x))
                (ty (getf spawn :y)))
            (when (and (numberp tx) (numberp ty))
              (let* ((x (round (* tx tile-size)))
                     (y (round (* ty tile-size)))
                     (cx (+ x (round (/ (- size dot) 2))))
                     (cy (+ y (round (/ (- size dot) 2)))))
                (raylib:draw-rectangle-lines x y size size *editor-spawn-color*)
                (raylib:draw-rectangle cx cy dot dot *editor-spawn-color*)))))))))

(defun draw-editor-cursor (editor world camera)
  ;; Draw the tile highlight under the mouse cursor.
  (multiple-value-bind (tx ty _wx _wy)
      (editor-mouse-tile editor world camera)
    (declare (ignore _wx _wy))
    (when (and (world-zone world)
               (zone-tile-in-bounds-p (world-zone world) tx ty))
      (let* ((tile-size (world-tile-dest-size world))
             (brush-w (if (member (editor-mode editor) '(:tile :collision))
                          (max 1 (editor-selection-width editor))
                          1))
             (brush-h (if (member (editor-mode editor) '(:tile :collision))
                          (max 1 (editor-selection-height editor))
                          1))
             (x (round (* tx tile-size)))
             (y (round (* ty tile-size)))
             (width (round (* tile-size brush-w)))
             (height (round (* tile-size brush-h))))
        (raylib:draw-rectangle-lines x y width height
                                     *editor-cursor-color*)))))

(defun draw-editor-world-overlay (editor world camera)
  ;; Draw editor overlays in world space.
  (when (editor-active editor)
    (draw-editor-spawns editor world)
    (draw-editor-cursor editor world camera)))

(defun draw-editor-ui-overlay (editor ui)
  ;; Draw editor UI hints in screen space.
  (when (editor-active editor)
    (let ((x 16)
          (y 40)
          (line 18))
      (when (editor-zone-label editor)
        (raylib:draw-text (editor-zone-label editor) x y 16 (ui-menu-text-color ui))
        (incf y line))
      (raylib:draw-text (editor-mode-label editor) x y 16 (ui-menu-text-color ui))
      (incf y line)
      (raylib:draw-text (editor-tileset-label-text editor) x y 16 (ui-menu-text-color ui))
      (incf y line)
      (raylib:draw-text (editor-tile-label editor) x y 16 (ui-menu-text-color ui))
      (incf y line)
      (raylib:draw-text (editor-object-label-text editor) x y 16 (ui-menu-text-color ui))
      (incf y line)
      (raylib:draw-text "1 tiles | 2 collision | 3 objects | 4 npcs | Q/E sheet (1/2) | Q/E object (3) | Q/E spawn (4) | click tile | shift+click block | F5 export" x y 16
                        (ui-menu-text-color ui))
      (incf y line)
      (raylib:draw-text "F6 new | F7 delete | F8/F9 cycle"
                        x y 16 (ui-menu-text-color ui))
      (incf y line)
      (raylib:draw-text "LMB paint | RMB erase" x y 16 (ui-menu-text-color ui))
      (when (editor-status-label editor)
        (incf y line)
        (raylib:draw-text (editor-status-label editor) x y 16
                          (ui-menu-text-color ui))))))
