(in-package #:mmorpg)

(defparameter *window-width* 1280)
(defparameter *window-height* 720)
(defparameter *player-size* 4)
(defparameter *player-speed* 120.0)

(defparameter +key-right+ (cffi:foreign-enum-value 'raylib:keyboard-key :right))
(defparameter +key-left+ (cffi:foreign-enum-value 'raylib:keyboard-key :left))
(defparameter +key-down+ (cffi:foreign-enum-value 'raylib:keyboard-key :down))
(defparameter +key-up+ (cffi:foreign-enum-value 'raylib:keyboard-key :up))
(defparameter +key-d+ (cffi:foreign-enum-value 'raylib:keyboard-key :d))
(defparameter +key-a+ (cffi:foreign-enum-value 'raylib:keyboard-key :a))
(defparameter +key-s+ (cffi:foreign-enum-value 'raylib:keyboard-key :s))
(defparameter +key-w+ (cffi:foreign-enum-value 'raylib:keyboard-key :w))

(defun move-player (x y dt)
  (let ((dx 0.0)
        (dy 0.0))
    (when (or (raylib:is-key-down +key-right+)
              (raylib:is-key-down +key-d+))
      (incf dx 1.0))
    (when (or (raylib:is-key-down +key-left+)
              (raylib:is-key-down +key-a+))
      (decf dx 1.0))
    (when (or (raylib:is-key-down +key-down+)
              (raylib:is-key-down +key-s+))
      (incf dy 1.0))
    (when (or (raylib:is-key-down +key-up+)
              (raylib:is-key-down +key-w+))
      (decf dy 1.0))
    (values (+ x (* dx *player-speed* dt))
            (+ y (* dy *player-speed* dt)))))

(defun clamp (value min-value max-value)
  (max min-value (min value max-value)))

(defun run ()
  (raylib:with-window ("Hello MMO" (*window-width* *window-height*))
    (raylib:set-target-fps 60)
    (let ((x (/ (- *window-width* *player-size*) 2.0))
          (y (/ (- *window-height* *player-size*) 2.0)))
      (loop :until (raylib:window-should-close)
            :do (let ((dt (raylib:get-frame-time)))
                  (multiple-value-setq (x y) (move-player x y dt))
                  (setf x (clamp x 0.0 (- *window-width* *player-size*)))
                  (setf y (clamp y 0.0 (- *window-height* *player-size*)))
                  (raylib:with-drawing
                    (raylib:clear-background raylib:+black+)
                    (raylib:draw-rectangle (truncate x) (truncate y)
                                           *player-size* *player-size*
                                           raylib:+white+)))))))
