;; rendering-ui.lisp — HUD overlays, minimap, debug info, chat rendering, inventory/equipment UI
(in-package #:mmorpg)

(defun draw-combat-log (ui start-x start-y)
  ;; Draw combat log lines when debug overlay is enabled.
  (let* ((buffer (ui-combat-log-buffer ui))
         (count (ui-combat-log-count ui))
         (cap (length buffer))
         (text-size (ui-combat-log-text-size ui))
         (line-height (+ text-size (ui-combat-log-line-gap ui))))
    (when (and (> cap 0) (> count 0))
      (let ((start (mod (- (ui-combat-log-index ui) count) cap)))
        (loop :for i :from 0 :below count
              :for index = (mod (+ start i) cap)
              :for text = (aref buffer index)
              :when (and text (not (string= text "")))
                :do (raylib:draw-text text
                                      start-x
                                      (+ start-y (* i line-height))
                                      text-size
                                      *debug-npc-text-color*))))))

(defun draw-hud-log (ui start-x start-y)
  ;; Draw HUD feedback lines in screen space.
  (let* ((buffer (ui-hud-log-buffer ui))
         (times (ui-hud-log-times ui))
         (count (ui-hud-log-count ui))
         (cap (length buffer))
         (text-size (ui-hud-log-text-size ui))
         (line-height (+ text-size (ui-hud-log-line-gap ui))))
    (when (and (> cap 0) (> count 0))
      (let ((start (mod (- (ui-hud-log-index ui) count) cap)))
        (let ((drawn 0))
          (loop :for i :from 0 :below count
                :for index = (mod (+ start i) cap)
                :for text = (aref buffer index)
                :for timer = (if times (aref times index) 0.0)
                :when (and text (not (string= text ""))
                           (> timer 0.0))
                  :do (let* ((fade (max 0.01 *hud-log-fade-seconds*))
                             (alpha (if (> timer fade)
                                        1.0
                                        (clamp (/ timer fade) 0.0 1.0)))
                             (color (raylib:fade raylib:+white+ alpha)))
                        (raylib:draw-text text
                                          start-x
                                          (+ start-y (* drawn line-height))
                                          text-size
                                          color)
                        (incf drawn))))))))

(defun draw-chat-input (ui start-x start-y)
  ;; Draw the active chat input line.
  (let* ((prompt (ui-chat-prompt ui))
         (buffer (ui-chat-buffer ui))
         (text (if (and buffer (> (length buffer) 0))
                   (format nil "~a ~a" prompt buffer)
                   (format nil "~a " prompt)))
         (text-size (ui-hud-log-text-size ui))
         (padding 6)
         (width (+ (* 9 (length text)) (* padding 2)))
         (height (+ text-size 8))
         (bg-color (ui-hud-bg-color ui)))
    (raylib:draw-rectangle (- start-x padding)
                           (- start-y 4)
                           width
                           height
                           bg-color)
    (raylib:draw-text text
                      start-x
                      start-y
                      text-size
                      (ui-menu-text-color ui))))

(defun draw-hud (player ui world)
  ;; Draw stamina HUD, zone label, and player stats.
  (let* ((labels (ui-stamina-labels ui))
         (max-index (1- (length labels)))
         (run-seconds (max 0 (min (truncate (player-run-stamina player))
                                  max-index)))
         (run-text (aref labels run-seconds))
         (zone-label (or (world-zone-label world) "NONE"))
         (zone-width (+ 60 (* 10 (length zone-label))))
         (hud-x 10)
         (hud-y 10)
         (stats-x hud-x)
         (stats-y 38))
    (raylib:draw-rectangle 6 6 110 24 (ui-hud-bg-color ui))
    (raylib:draw-text run-text hud-x hud-y 20 raylib:+white+)
    (raylib:draw-rectangle 122 6 zone-width 24 (ui-hud-bg-color ui))
    (raylib:draw-text "Zone" 128 hud-y 20 raylib:+white+)
    (raylib:draw-text zone-label 176 hud-y 20 raylib:+white+)
    ;; FPS and Ping display (top-right corner)
    (let* ((fps (raylib:get-fps))
           (ping-ms (ui-ping-rtt-ms ui))
           (stats-text (if ping-ms
                           (format nil "~dms | ~d FPS" ping-ms fps)
                           (format nil "~d FPS" fps)))
           (stats-width (+ 20 (* 10 (length stats-text))))
           (stats-x (- (current-screen-width) stats-width 6)))
      (raylib:draw-rectangle stats-x 6 stats-width 24 (ui-hud-bg-color ui))
      (raylib:draw-text stats-text (+ stats-x 10) hud-y 20 raylib:+white+))
    (let ((hover-name (ui-hover-npc-name ui)))
      (when hover-name
        (let* ((text-size 20)
               (padding 10)
               (width (+ (* 10 (length hover-name)) (* padding 2)))
               (x (truncate (/ (- (current-screen-width) width) 2)))
               (y 6))
          (raylib:draw-rectangle x y width 24 (ui-hud-bg-color ui))
          (raylib:draw-text hover-name
                            (+ x padding)
                            hud-y
                            text-size
                            raylib:+white+))))
    (ensure-player-hud-stats player)
    (let* ((lines (player-hud-stats-lines player))
           (count (player-hud-stats-count player))
           (text-size (ui-hud-stats-text-size ui))
           (line-height (+ text-size (ui-hud-stats-line-gap ui)))
           (log-start-y (+ stats-y (* count line-height) 6))
           (chat-active (ui-chat-active ui))
           (log-offset (if chat-active
                           (+ (ui-hud-log-text-size ui)
                              (ui-hud-log-line-gap ui)
                              8)
                           0)))
      (when lines
        (loop :for i :from 0 :below count
              :for text = (aref lines i)
              :do (raylib:draw-text text
                                    stats-x
                                    (+ stats-y (* i line-height))
                                    text-size
                                    raylib:+white+))
        (when chat-active
          (draw-chat-input ui stats-x log-start-y))
        (if *debug-collision-overlay*
            (draw-combat-log ui
                             stats-x
                             (+ log-start-y log-offset))
            (draw-hud-log ui
                          stats-x
                          (+ log-start-y log-offset)))))))

(defun draw-inventory (player ui render assets)
  ;; Draw the inventory overlay when enabled.
  (when (and player (ui-inventory-open ui))
    (let* ((inventory (player-inventory player))
           (slots (and inventory (inventory-slots inventory)))
           (slot-count (if slots (length slots) 0))
           (title-size 24)
           (count-size 12)
           (panel-color (ui-menu-panel-color ui))
           (text-color (ui-menu-text-color ui))
           (slot-color (raylib:fade (ui-menu-panel-color ui) 0.7))
           (slot-border (ui-menu-text-color ui))
           ;; Drag state
           (dragging (ui-drag-active ui))
           (drag-source-slot (and dragging (ui-drag-slot-index ui)))
           (drag-item-id (and dragging (ui-drag-item-id ui)))
           (mouse-x (virtual-mouse-x))
           (mouse-y (virtual-mouse-y))
           ;; Colors for drag feedback
           (dimmed-slot-color (raylib:fade slot-color 0.3))
           (highlight-color (raylib:make-color :r 255 :g 255 :b 100 :a 100)))
      (multiple-value-bind (grid-x grid-y slot-size gap columns rows
                            panel-x panel-y panel-width panel-height header-height padding)
          (inventory-grid-layout ui slot-count)
        (declare (ignore rows header-height))
        (raylib:draw-rectangle panel-x panel-y panel-width panel-height panel-color)
        (raylib:draw-rectangle-lines panel-x panel-y panel-width panel-height text-color)
        (raylib:draw-text "Inventory"
                          (+ panel-x padding)
                          (+ panel-y padding)
                          title-size
                          text-color)
        (let ((source (render-tile-source render))
              (dest (render-tile-dest render))
              (origin (render-origin render))
              (hover-slot nil))
          ;; Determine which slot mouse is hovering over (for drag target highlight)
          (when dragging
            (dotimes (index slot-count)
              (let* ((col (mod index columns))
                     (row (floor index columns))
                     (slot-x (+ grid-x (* col (+ slot-size gap))))
                     (slot-y (+ grid-y (* row (+ slot-size gap)))))
                (when (and (>= mouse-x slot-x) (< mouse-x (+ slot-x slot-size))
                           (>= mouse-y slot-y) (< mouse-y (+ slot-y slot-size)))
                  (setf hover-slot index)))))
          ;; Draw slots
          (dotimes (index slot-count)
            (let* ((col (mod index columns))
                   (row (floor index columns))
                   (slot-x (+ grid-x (* col (+ slot-size gap))))
                   (slot-y (+ grid-y (* row (+ slot-size gap))))
                   ;; Dim source slot, highlight hover slot
                   (is-source (and dragging (eql index drag-source-slot)))
                   (is-hover-target (and dragging hover-slot (eql index hover-slot)
                                         (not is-source)))
                   (current-slot-color (if is-source dimmed-slot-color slot-color)))
              (raylib:draw-rectangle slot-x slot-y slot-size slot-size current-slot-color)
              ;; Draw highlight for hover target
              (when is-hover-target
                (raylib:draw-rectangle slot-x slot-y slot-size slot-size highlight-color))
              (raylib:draw-rectangle-lines slot-x slot-y slot-size slot-size slot-border)
              ;; Draw item (skip rendering item in source slot if dragging)
              (when (and slots (< index (length slots)) (not is-source))
                (let* ((slot (aref slots index))
                       (item-id (inventory-slot-item-id slot))
                       (count (inventory-slot-count slot)))
                  (when (and item-id (> count 0))
                    (let* ((texture (item-texture-for assets item-id))
                           (dest-x (float slot-x 1.0))
                           (dest-y (float slot-y 1.0))
                           (dest-size (float slot-size 1.0)))
                      (if texture
                          (let ((src-w (float (raylib:texture-width texture) 1.0))
                                (src-h (float (raylib:texture-height texture) 1.0)))
                            (set-rectangle source 0.0 0.0 src-w src-h)
                            (set-rectangle dest dest-x dest-y dest-size dest-size)
                            (raylib:draw-texture-pro texture
                                                     source
                                                     dest
                                                     origin
                                                     0.0
                                                     raylib:+white+))
                          (let* ((item (find-item-archetype item-id))
                                 (label (or (and item (item-archetype-name item))
                                            (string-capitalize (string item-id)))))
                            (raylib:draw-text label
                                              (+ slot-x 4)
                                              (+ slot-y 4)
                                              10
                                              text-color))))
                    (let ((count-text (format nil "~d" count)))
                      (raylib:draw-text count-text
                                        (+ slot-x (- slot-size 18))
                                        (+ slot-y (- slot-size 16))
                                        count-size
                                        text-color)))))))
          ;; Draw dragged item at cursor position (last, so it's on top)
          (when (and dragging drag-item-id)
            (let* ((texture (item-texture-for assets drag-item-id))
                   (half-size (floor slot-size 2))
                   (drag-dest-x (float (- mouse-x half-size) 1.0))
                   (drag-dest-y (float (- mouse-y half-size) 1.0))
                   (drag-dest-size (float slot-size 1.0)))
              (if texture
                  (let ((src-w (float (raylib:texture-width texture) 1.0))
                        (src-h (float (raylib:texture-height texture) 1.0)))
                    (set-rectangle source 0.0 0.0 src-w src-h)
                    (set-rectangle dest drag-dest-x drag-dest-y drag-dest-size drag-dest-size)
                    (raylib:draw-texture-pro texture
                                             source
                                             dest
                                             origin
                                             0.0
                                             (raylib:fade raylib:+white+ 0.8)))
                  (let* ((item (find-item-archetype drag-item-id))
                         (label (or (and item (item-archetype-name item))
                                    (string-capitalize (string drag-item-id)))))
                    (raylib:draw-text label
                                      (truncate drag-dest-x)
                                      (truncate drag-dest-y)
                                      14
                                      text-color))))))))))

(defun minimap-world-to-screen (ui world player world-x world-y)
  ;; Convert world coordinates into minimap screen space.
  (multiple-value-bind (view-min-x view-min-y span-x span-y)
      (minimap-view-bounds world player)
    (let* ((rx (if (> span-x 0.0)
                   (/ (- world-x view-min-x) span-x)
                   0.0))
           (ry (if (> span-y 0.0)
                   (/ (- world-y view-min-y) span-y)
                   0.0)))
      (if (and (<= 0.0 rx) (<= rx 1.0)
               (<= 0.0 ry) (<= ry 1.0))
          (values (+ (ui-minimap-x ui) (* rx (ui-minimap-width ui)))
                  (+ (ui-minimap-y ui) (* ry (ui-minimap-height ui))))
          (values nil nil)))))

(defun ensure-minimap-data (world)
  ;; Lazily rebuild minimap data deferred from zone transitions.
  ;; Called at draw time so the sim tick stays fast (avoids audio skips).
  (when (world-minimap-dirty world)
    (setf (world-minimap-spawns world)
          (build-adjacent-minimap-spawns world))
    (setf (world-minimap-collisions world)
          (build-minimap-collisions world))
    (setf (world-minimap-dirty world) nil)))

(defun draw-minimap (world player npcs ui)
  ;; Render the minimap overlay and markers.
  (ensure-minimap-data world)
  (let* ((map-x (ui-minimap-x ui))
         (map-y (ui-minimap-y ui))
         (map-width (ui-minimap-width ui))
         (map-height (ui-minimap-height ui))
         (point-size (ui-minimap-point-size ui))
         (half (truncate (/ point-size 2))))
    (raylib:draw-rectangle map-x map-y map-width map-height
                           (ui-minimap-bg-color ui))
    (raylib:draw-rectangle-lines map-x map-y map-width map-height
                                 (ui-minimap-border-color ui))
    (let* ((collisions (world-minimap-collisions world))
           (collision-size (max 1 (truncate (/ point-size 2))))
           (collision-half (truncate (/ collision-size 2))))
      (when (and collisions (> (length collisions) 0))
        (loop :for i :from 0 :below (length collisions) :by 2
              :for wx = (aref collisions i)
              :for wy = (aref collisions (1+ i))
              :do (multiple-value-bind (sx sy)
                      (minimap-world-to-screen ui world player wx wy)
                    (when (and sx sy)
                      (raylib:draw-rectangle (- (truncate sx) collision-half)
                                             (- (truncate sy) collision-half)
                                             collision-size
                                             collision-size
                                             (ui-minimap-collision-color ui)))))))
    (multiple-value-bind (px py)
        (minimap-world-to-screen ui world player (player-x player) (player-y player))
      (when (and px py)
        (raylib:draw-rectangle (- (truncate px) half)
                               (- (truncate py) half)
                               point-size
                               point-size
                               (ui-minimap-player-color ui))))
    ;; Draw NPCs within minimap view radius (squared distance check avoids sqrt)
    (let* ((player-x (player-x player))
           (player-y (player-y player))
           (radius-sq (* *minimap-npc-view-radius* *minimap-npc-view-radius*)))
      (loop :for npc :across npcs
            :when (npc-alive npc)
            :do (let* ((dx (- (npc-x npc) player-x))
                       (dy (- (npc-y npc) player-y))
                       (dist-sq (+ (* dx dx) (* dy dy))))
                  (when (<= dist-sq radius-sq)
                    (multiple-value-bind (nx ny)
                        (minimap-world-to-screen ui world player (npc-x npc) (npc-y npc))
                      (when (and nx ny)
                        (raylib:draw-rectangle (- (truncate nx) half)
                                               (- (truncate ny) half)
                                               point-size
                                               point-size
                                               (ui-minimap-npc-color ui))))))))
    (let* ((preview (world-minimap-spawns world))
           (preview-size (max 2 (truncate (/ point-size 2))))
           (preview-half (truncate (/ preview-size 2)))
           (preview-edge (world-preview-edge world player))
           (preview-exit (and preview-edge (world-edge-exit world preview-edge))))
      (when preview-exit
        (dolist (entry preview)
          (destructuring-bind (edge px py) entry
            (when (eq edge preview-edge)
              (multiple-value-bind (sx sy)
                  (minimap-world-to-screen ui world player px py)
                (when (and sx sy)
                  (raylib:draw-rectangle (- (truncate sx) preview-half)
                                         (- (truncate sy) preview-half)
                                         preview-size
                                         preview-size
                                         (ui-minimap-npc-color ui)))))))))))

(defun draw-loading-overlay (ui)
  ;; Draw a brief loading label while zones swap.
  (when (> (ui-loading-timer ui) 0.0)
    (let* ((label (ui-loading-label ui))
           (font-size 22)
           (padding 16)
           (text-width (truncate (* (length label) (* font-size 0.6))))
           (box-width (+ text-width (* padding 2)))
           (box-height (+ font-size (* padding 2)))
           (box-x (truncate (- (/ (current-screen-width) 2) (/ box-width 2))))
           (box-y (truncate (- (/ (current-screen-height) 2) (/ box-height 2))))
           (text-x (+ box-x padding))
           (text-y (+ box-y padding)))
      (raylib:draw-rectangle box-x box-y box-width box-height
                             (ui-menu-panel-color ui))
      (raylib:draw-text label text-x text-y font-size
                        (ui-menu-text-color ui)))))

(defun draw-editor-tileset-preview (editor render)
  ;; Draw the active tileset sheet in screen space for tile picking.
  (when (and editor (editor-active editor))
    (multiple-value-bind (x y w h scale tileset)
        (editor-tileset-preview-layout editor)
      (when (and x tileset)
        (let* ((texture (editor-tileset-texture tileset))
               (source (render-tile-source render))
               (dest (render-tile-dest render))
               (origin (render-origin render)))
          (raylib:draw-rectangle (round x) (round y) (round w) (round h)
                                 *editor-tileset-preview-bg-color*)
          (set-rectangle source 0.0 0.0
                         (float (raylib:texture-width texture) 1.0)
                         (float (raylib:texture-height texture) 1.0))
          (set-rectangle dest x y w h)
          (raylib:draw-texture-pro texture source dest origin 0.0 raylib:+white+)
          (raylib:draw-rectangle-lines (round x) (round y) (round w) (round h)
                                       *editor-tileset-preview-border-color*)
          (let* ((tile-size (* (max 1.0 (float *tile-size* 1.0)) scale))
                 (columns (max 1 (editor-tileset-columns tileset)))
                 (rows (max 1 (editor-tileset-rows tileset)))
                 (tile-index (editor-selected-tile editor))
                 (tx (mod tile-index columns))
                 (ty (floor tile-index columns))
                 (sel-w (min (max 1 (editor-selection-width editor))
                             (max 1 (- columns tx))))
                 (sel-h (min (max 1 (editor-selection-height editor))
                             (max 1 (- rows ty)))))
            (when (and (> tile-size 0.0)
                       (<= 0 tx) (< tx columns)
                       (<= 0 ty) (< ty rows))
              (let ((sel-x (+ x (* tx tile-size)))
                    (sel-y (+ y (* ty tile-size)))
                    (sel-w-px (* tile-size sel-w))
                    (sel-h-px (* tile-size sel-h)))
                (raylib:draw-rectangle-lines (round sel-x) (round sel-y)
                                             (round sel-w-px) (round sel-h-px)
                                             *editor-tileset-preview-highlight-color*)))))))))

(defun draw-menu (ui audio editor)
  ;; Render the pause menu and hover states.
  (let* ((mouse-x (virtual-mouse-x))
         (mouse-y (virtual-mouse-y))
         (hover-logout (point-in-rect-p mouse-x mouse-y
                                        (ui-menu-logout-x ui)
                                        (ui-menu-logout-y ui)
                                        (ui-menu-logout-width ui)
                                        (ui-menu-logout-height ui)))
         (hover-unstuck (point-in-rect-p mouse-x mouse-y
                                         (ui-menu-unstuck-x ui)
                                         (ui-menu-unstuck-y ui)
                                         (ui-menu-unstuck-width ui)
                                         (ui-menu-unstuck-height ui)))
         (hover-prev (point-in-rect-p mouse-x mouse-y
                                      (ui-menu-prev-x ui)
                                      (ui-menu-nav-y ui)
                                      (ui-menu-nav-button-width ui)
                                      (ui-menu-nav-button-height ui)))
         (hover-next (point-in-rect-p mouse-x mouse-y
                                      (ui-menu-next-x ui)
                                      (ui-menu-nav-y ui)
                                      (ui-menu-nav-button-width ui)
                                      (ui-menu-nav-button-height ui)))
         (hover-vol-down (point-in-rect-p mouse-x mouse-y
                                          (ui-menu-volume-down-x ui)
                                          (ui-menu-volume-y ui)
                                          (ui-menu-volume-button-width ui)
                                          (ui-menu-volume-button-height ui)))
         (hover-vol-up (point-in-rect-p mouse-x mouse-y
                                        (ui-menu-volume-up-x ui)
                                        (ui-menu-volume-y ui)
                                        (ui-menu-volume-button-width ui)
                                        (ui-menu-volume-button-height ui)))
         (logout-color (if hover-logout
                           (ui-menu-button-hover-color ui)
                           (ui-menu-button-color ui)))
         (unstuck-color (if hover-unstuck
                            (ui-menu-button-hover-color ui)
                            (ui-menu-button-color ui)))
         (prev-color (if hover-prev
                         (ui-menu-button-hover-color ui)
                         (ui-menu-button-color ui)))
         (next-color (if hover-next
                         (ui-menu-button-hover-color ui)
                         (ui-menu-button-color ui)))
         (vol-down-color (if hover-vol-down
                             (ui-menu-button-hover-color ui)
                             (ui-menu-button-color ui)))
         (vol-up-color (if hover-vol-up
                           (ui-menu-button-hover-color ui)
                           (ui-menu-button-color ui)))
         (title-x (+ (ui-menu-panel-x ui) (ui-menu-padding ui)))
         (title-y (+ (ui-menu-panel-y ui) (ui-menu-padding ui)))
         (hint-y (+ (ui-menu-panel-y ui) (ui-menu-padding ui) 44))
         (track-title-y (- (ui-menu-nav-y ui) 28))
         (volume-label-y (- (ui-menu-volume-y ui) 26))
         (volume-bars-text (aref (audio-volume-bars audio)
                                 (audio-volume-level audio)))
         (debug-on *debug-collision-overlay*)
         (hover-debug (point-in-rect-p mouse-x mouse-y
                                       (ui-menu-debug-x ui)
                                       (ui-menu-debug-y ui)
                                       (ui-menu-debug-size ui)
                                       (ui-menu-debug-size ui)))
         (editor-on (and editor (editor-active editor)))
         (hover-editor (point-in-rect-p mouse-x mouse-y
                                        (ui-menu-editor-x ui)
                                        (ui-menu-editor-y ui)
                                        (ui-menu-editor-size ui)
                                        (ui-menu-editor-size ui)))
         (fs-on (raylib:is-window-fullscreen))
         (hover-fs (point-in-rect-p mouse-x mouse-y
                                    (ui-menu-fullscreen-x ui)
                                    (ui-menu-fullscreen-y ui)
                                    (ui-menu-fullscreen-size ui)
                                    (ui-menu-fullscreen-size ui)))
         (leash-on *camera-leash-enabled*)
         (hover-leash (point-in-rect-p mouse-x mouse-y
                                       (ui-menu-leash-x ui)
                                       (ui-menu-leash-y ui)
                                       (ui-menu-leash-size ui)
                                       (ui-menu-leash-size ui)))
         (debug-box-color (cond
                            (hover-debug (ui-menu-button-hover-color ui))
                            (debug-on (ui-menu-button-color ui))
                            (t (ui-menu-panel-color ui))))
         (editor-box-color (cond
                             (hover-editor (ui-menu-button-hover-color ui))
                             (editor-on (ui-menu-button-color ui))
                             (t (ui-menu-panel-color ui))))
         (fs-box-color (cond
                         (hover-fs (ui-menu-button-hover-color ui))
                         (fs-on (ui-menu-button-color ui))
                         (t (ui-menu-panel-color ui))))
         (leash-box-color (cond
                            (hover-leash (ui-menu-button-hover-color ui))
                            (leash-on (ui-menu-button-color ui))
                            (t (ui-menu-panel-color ui)))))
    (raylib:draw-rectangle 0 0 (current-screen-width) (current-screen-height)
                           (ui-menu-overlay-color ui))
    (raylib:draw-rectangle (ui-menu-panel-x ui) (ui-menu-panel-y ui)
                           (ui-menu-panel-width ui) (ui-menu-panel-height ui)
                           (ui-menu-panel-color ui))
    (raylib:draw-text (ui-menu-title ui)
                      title-x
                      title-y
                      (ui-menu-title-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-text (ui-menu-hint ui)
                      title-x
                      hint-y
                      (ui-menu-hint-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-text (ui-menu-track-title ui)
                      title-x
                      track-title-y
                      (ui-menu-track-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-prev-x ui) (ui-menu-nav-y ui)
                           (ui-menu-nav-button-width ui)
                           (ui-menu-nav-button-height ui)
                           prev-color)
    (raylib:draw-text (ui-menu-prev-label ui)
                      (+ (ui-menu-prev-x ui) 18)
                      (+ (ui-menu-nav-y ui) 12)
                      (ui-menu-nav-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-next-x ui) (ui-menu-nav-y ui)
                           (ui-menu-nav-button-width ui)
                           (ui-menu-nav-button-height ui)
                           next-color)
    (raylib:draw-text (ui-menu-next-label ui)
                      (+ (ui-menu-next-x ui) 18)
                      (+ (ui-menu-nav-y ui) 12)
                      (ui-menu-nav-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-text (audio-current-track-label audio)
                      (ui-menu-track-text-x ui)
                      (ui-menu-track-text-y ui)
                      (ui-menu-track-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-text "Volume"
                      (ui-menu-track-text-x ui)
                      volume-label-y
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-volume-down-x ui)
                           (ui-menu-volume-y ui)
                           (ui-menu-volume-button-width ui)
                           (ui-menu-volume-button-height ui)
                           vol-down-color)
    (raylib:draw-text (ui-menu-vol-down-label ui)
                      (+ (ui-menu-volume-down-x ui) 14)
                      (+ (ui-menu-volume-y ui) 10)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-volume-up-x ui)
                           (ui-menu-volume-y ui)
                           (ui-menu-volume-button-width ui)
                           (ui-menu-volume-button-height ui)
                           vol-up-color)
    (raylib:draw-text (ui-menu-vol-up-label ui)
                      (+ (ui-menu-volume-up-x ui) 14)
                      (+ (ui-menu-volume-y ui) 10)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-text volume-bars-text
                      (ui-menu-volume-bars-x ui)
                      (+ (ui-menu-volume-y ui) 10)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-debug-x ui)
                           (ui-menu-debug-y ui)
                           (ui-menu-debug-size ui)
                           (ui-menu-debug-size ui)
                           debug-box-color)
    (raylib:draw-rectangle-lines (ui-menu-debug-x ui)
                                 (ui-menu-debug-y ui)
                                 (ui-menu-debug-size ui)
                                 (ui-menu-debug-size ui)
                                 (ui-menu-text-color ui))
    (raylib:draw-text (ui-menu-debug-label ui)
                      (+ (ui-menu-debug-x ui) 28)
                      (- (ui-menu-debug-y ui) 2)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-editor-x ui)
                           (ui-menu-editor-y ui)
                           (ui-menu-editor-size ui)
                           (ui-menu-editor-size ui)
                           editor-box-color)
    (raylib:draw-rectangle-lines (ui-menu-editor-x ui)
                                 (ui-menu-editor-y ui)
                                 (ui-menu-editor-size ui)
                                 (ui-menu-editor-size ui)
                                 (ui-menu-text-color ui))
    (raylib:draw-text (ui-menu-editor-label ui)
                      (+ (ui-menu-editor-x ui) 28)
                      (- (ui-menu-editor-y ui) 2)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    (raylib:draw-rectangle (ui-menu-fullscreen-x ui)
                           (ui-menu-fullscreen-y ui)
                           (ui-menu-fullscreen-size ui)
                           (ui-menu-fullscreen-size ui)
                           fs-box-color)
    (raylib:draw-rectangle-lines (ui-menu-fullscreen-x ui)
                                 (ui-menu-fullscreen-y ui)
                                 (ui-menu-fullscreen-size ui)
                                 (ui-menu-fullscreen-size ui)
                                 (ui-menu-text-color ui))
    (raylib:draw-text (ui-menu-fullscreen-label ui)
                      (+ (ui-menu-fullscreen-x ui) 28)
                      (- (ui-menu-fullscreen-y ui) 2)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    ;; Camera leash toggle
    (raylib:draw-rectangle (ui-menu-leash-x ui)
                           (ui-menu-leash-y ui)
                           (ui-menu-leash-size ui)
                           (ui-menu-leash-size ui)
                           leash-box-color)
    (raylib:draw-rectangle-lines (ui-menu-leash-x ui)
                                 (ui-menu-leash-y ui)
                                 (ui-menu-leash-size ui)
                                 (ui-menu-leash-size ui)
                                 (ui-menu-text-color ui))
    (raylib:draw-text (ui-menu-leash-label ui)
                      (+ (ui-menu-leash-x ui) 28)
                      (- (ui-menu-leash-y ui) 2)
                      (ui-menu-volume-text-size ui)
                      (ui-menu-text-color ui))
    ;; Unstuck button (above logout)
    (raylib:draw-rectangle (ui-menu-unstuck-x ui) (ui-menu-unstuck-y ui)
                           (ui-menu-unstuck-width ui)
                           (ui-menu-unstuck-height ui)
                           unstuck-color)
    (raylib:draw-text (ui-menu-unstuck-label ui)
                      (+ (ui-menu-unstuck-x ui) 24)
                      (+ (ui-menu-unstuck-y ui) 16)
                      (ui-menu-button-text-size ui)
                      (ui-menu-text-color ui))
    ;; Logout button
    (raylib:draw-rectangle (ui-menu-logout-x ui) (ui-menu-logout-y ui)
                           (ui-menu-logout-width ui)
                           (ui-menu-logout-height ui)
                           logout-color)
    (raylib:draw-text (ui-menu-logout-label ui)
                      (+ (ui-menu-logout-x ui) 24)
                      (+ (ui-menu-logout-y ui) 16)
                      (ui-menu-button-text-size ui)
                      (ui-menu-text-color ui))))

(defun draw-context-menu (ui)
  ;; Render the right-click context menu.
  (when (ui-context-open ui)
    (let* ((x (ui-context-x ui))
           (y (ui-context-y ui))
           (width (ui-context-width ui))
           (option-height (ui-context-option-height ui))
           (padding (ui-context-padding ui))
           (text-size (ui-context-text-size ui))
           (count (context-menu-option-count ui))
           (height (* count option-height))
           (text-color (ui-menu-text-color ui))
           (panel-color (ui-menu-panel-color ui))
           (mouse-x (virtual-mouse-x))
           (mouse-y (virtual-mouse-y))
           (hover-index (when (point-in-rect-p mouse-x mouse-y x y width height)
                          (floor (/ (- mouse-y y) option-height))))
           (hover-color (raylib:fade (ui-menu-button-hover-color ui) 0.6)))
      (raylib:draw-rectangle x y width height panel-color)
      (raylib:draw-rectangle-lines x y width height text-color)
      (let ((option-index 0)
            (actions (context-menu-actions ui)))
        (labels ((label-for (action)
                   (ecase action
                     (:walk (ui-context-walk-label ui))
                     (:attack (ui-context-attack-label ui))
                     (:follow (ui-context-follow-label ui))
                     (:pickup (ui-context-pickup-label ui))
                     (:examine (ui-context-examine-label ui))
                     (:drop (ui-context-drop-label ui))))
                 (draw-option (action)
                   (let ((option-y (+ y (* option-height option-index))))
                     (when (and hover-index (= hover-index option-index))
                       (raylib:draw-rectangle x option-y width option-height hover-color))
                     (raylib:draw-text (label-for action)
                                       (+ x padding)
                                       (+ option-y padding)
                                       text-size
                                       text-color))
                   (incf option-index)))
          (dolist (action actions)
            (draw-option action)))))))
